package ar.noxit.ehockey.model;

public interface Rol {

    static final String HOME = "HOME";
    static final String BUENA_FE = "PRINCIPAL_LBF";
    static final String VER_BUENA_FE = "VER_LBF";
    static final String EDITAR_BUENA_FE = "EDITAR_LBF";

    static final String TORNEOS = "PRINCIPAL_TORNEOS";
    static final String CREAR_TORNEOS = "CREAR_TORNEOS";
    static final String VER_TORNEOS = "VER_TORNEOS";
    static final String VER_PARTIDOS_TORNEOS = "PARTIDOS_TORNEOS";
    static final String VER_PLANILLAS_PRECARGADAS_TORNEOS = "PLANILLAS_PRE_TORNEOS";
    static final String VER_PLANILLAS_FINALES_TORNEOS = "PLANILLAS_FIN_TORNEOS";
    static final String TERMINAR_PARTIDO = "TERMINAR_PARTIDO";
    static final String REPROGRAMAR_PARTIDO = "REPROGRAMAR_PARTIDO";

    static final String JUGADORES = "PRINCIPAL_JUGADORES";
    static final String ALTA_JUGADORES = "ALTA_JUGADORES";
    static final String LISTA_JUGADORES = "LISTA_JUGADORES";
    static final String ACTUALIZACION_JUGADORES = "ACTUALIZACION_JUGADORES";
    static final String BAJA_JUGADORES = "BAJA_JUGADORES";

    static final String TABLA_POSICIONES = "PRINCIPAL_TABLA";

    static final String USUARIOS = "PRINCIPAL_USUARIOS";
    static final String ALTA_USUARIOS = "ALTA_USUARIOS";
    static final String MODIF_USUARIOS = "MODIFICACION_USUARIOS";
    static final String BAJA_USUARIOS = "BAJA_USUARIOS";

    static final String FECHA_HORA = "PRINCIPAL_FECHA_HORA";

    static final String MENSAJE = "MENSAJE";

    static final String GUEST = "guest";

    static final String[] ADMIN = { HOME, BUENA_FE, VER_BUENA_FE, EDITAR_BUENA_FE, TORNEOS, CREAR_TORNEOS, VER_TORNEOS,
            VER_PARTIDOS_TORNEOS, VER_PLANILLAS_PRECARGADAS_TORNEOS, VER_PLANILLAS_FINALES_TORNEOS, JUGADORES,
            ALTA_JUGADORES, LISTA_JUGADORES, ACTUALIZACION_JUGADORES, BAJA_JUGADORES, TABLA_POSICIONES, USUARIOS,
            ALTA_USUARIOS, MODIF_USUARIOS, BAJA_USUARIOS, FECHA_HORA, MENSAJE, TERMINAR_PARTIDO, REPROGRAMAR_PARTIDO };

    static final String[] REPRESENTANTE = { HOME, BUENA_FE, VER_BUENA_FE, EDITAR_BUENA_FE, TORNEOS, VER_TORNEOS,
            VER_PARTIDOS_TORNEOS, VER_PLANILLAS_PRECARGADAS_TORNEOS, VER_PLANILLAS_FINALES_TORNEOS, JUGADORES,
            ALTA_JUGADORES, LISTA_JUGADORES, ACTUALIZACION_JUGADORES, BAJA_JUGADORES, TABLA_POSICIONES, MENSAJE };

}
